THEORY QUESTIONS

Q.1 Explain the purpose and advantage of NumPy in scientific computing and data analysis.How does it enhances python's capabilities for numerical operations?
Purpose and Advantages:
NumPy is powerful library for numerical computation.It provides support for multi-dimensional arrays and matrices,along with a collection of mathematical function to operate on these arrays.
Enhancements to python
Efficiency: NumPy arrays are more efficient than the python lists for large data sets as they uses less memory and allow faster data processing.
Vectorised operation: Numpy allows element wise operation without the use of vectorised loop.
Integration: NumPy integrates well with other scientific computing libraries such as SciPy and pandas,and is essential for machine learning and data analysing.

Q2.Compare and contrast np.mean() and np.average() functions in NumPy.When would You use one over the other?

np.mean(): Calcuates mean of the array element along the specified axis excluding weights.
np.average(): Calculates weighted average.

When to use:
Use np.mean()to claculate simple avearge. use np.avearge() when weight is given.

Q3.Describe the methods for reversing a Numpy array along different axes.Provide examples for 1D and 2D array.

Reversing in 1D: Use slicing.Eg..arr[::-1]

Reversing in 2D: Rowwise(axis 0): arr[::-1,:] column-wise(axis 1): arr[:,::-1]

In [6]:
import numpy as np

# 1D array
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_arr_1d = arr_1d[::-1]
print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


Q4.How can you determine the data type of elements in a numPy array?Discuss the importance of data types in memory management and performance.
Determining data type:
Use the dtype attribute. eg..arr.dtype.
Importance:
Specifying data types helps in optimizing memory usage and computational speed,as smaller dta types use less,memory. Using appropriate data types improves performance.

Q5.Q.5 Define ndarrays in numpy and explain their key features.How do they differ from standard python lists?
Ans.ndarray (n-dimensional array) : It is a grid of values witha specified number of dimensions and a fixed size.Each element in the ndarray has same data type.

Key features of ndarray :
Suports mathematical and logical operations.
Faster and more memory-efficient than python lists.
Difference from python lists: Unlike lists, ndarrays suport vectorised operation and have homogenous data types,which allow for efficient computation.

Q6.Analyse the performance benefits of Numpy arrays over python lists over large scale numerical operations.
Ans.
Memory efficiency :Numpy arrays consume less memory than lists as they are stored in contigous blocks.
Speed : Numpy operation are faster becuse they are implemented in C and involves fewer function calls.
Vectorised operation :Element wise operations on arrays eliminate the python loops,further improving the performance.

Q7.Q.7 Compare vstack() and hstack() functions in numpy.Provide examples demonstrating their usage and output.
Ans.
vstack(): stacks arrays vertically(along rows).
hstack(): stacks arrays horizontally(along columns).

In [7]:
arr1=np.array([1,2])
arr2=np.array([3,4])
np.vstack((arr1,arr2))
np.hstack((arr1,arr2))

array([1, 2, 3, 4])

Q8.Explain the differnce between fliplr() and flipud() methods in numpy including their effects on various array dimensions.
Ans.
flipud(): Flips the array verticall up to down. Equvalent to reversing the order of rows.
fliplr(): Flips the array horizontally left to right.Equivalent to reversing the order of columns.

In [9]:
arr=np.array([[1,2],[3,5]])
np.flipud(arr)

array([[3, 5],
       [1, 2]])

Q9.Q.9 Discuss the functionality of the array_split() method in numPy.how does it handle uneven split?
Ans.
Functionality : array_split() divides an array into subarrays.It is useful when number of sections does not evenly divide the array.
Uneven splits : If the array does not divide evenly,the final sub arrays will be smaller than the others.

In [ ]:
arr = np.array([1,2,3,4,5])
np.array_split(arr,3)

Q.10 Explain the concepts of vectorization and broadcasting in numpy.How do they contribute to efficent array operations?
Ans.
Vectorization: Eliminates explicit loops by applying operations directly on arrays.
Broadcasting :Expands the dimensions of smaller arrays to match larger arrays,allowing element-wise operations on differntly shaped arrays.
Efficiency : Both techniques minimize the need for python loops,making coputations faster and more memory-efficient.

PRACTICAL QUESTIONS

Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [10]:
import numpy as np
array=np.random.randint(1,101,size =(3,3))
print("Original array: \n",array)

Original array: 
 [[59 99 69]
 [69 18 81]
 [59  4 96]]


In [11]:
Trans_array =array.T
print("Transposed array:\n",Trans_array)

Transposed array:
 [[59 69 59]
 [99 18  4]
 [69 81 96]]


Q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [12]:
import numpy as np
arr_1d=np.arange(10)
print("1D Array:\n",arr_1d)

1D Array:
 [0 1 2 3 4 5 6 7 8 9]


In [13]:
arr_2x5=arr_1d.reshape(2,5)
print("2x5 Array :\n",arr_2x5)

2x5 Array :
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [14]:
arr_5x2=arr_1d.reshape(5,2)
print("5x2 Array :\n",arr_5x2)

5x2 Array :
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [17]:
arr_4x4=np.random.rand(4,4)
print("4x4 Array :\n",arr_4x4)


4x4 Array :
 [[0.00112937 0.57709043 0.22385288 0.63071067]
 [0.30293199 0.06783061 0.95718404 0.99029056]
 [0.21442371 0.38279942 0.38553917 0.32647052]
 [0.61705179 0.83246259 0.84717459 0.62816728]]


In [18]:
arr_6x6=np.pad(arr_4x4,pad_width=1,mode='constant',constant_values=0)
print("6x6 Array with zero border :\n",arr_6x6)

6x6 Array with zero border :
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.00112937 0.57709043 0.22385288 0.63071067 0.        ]
 [0.         0.30293199 0.06783061 0.95718404 0.99029056 0.        ]
 [0.         0.21442371 0.38279942 0.38553917 0.32647052 0.        ]
 [0.         0.61705179 0.83246259 0.84717459 0.62816728 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [16]:
arr5=np.arange(10,61,5)
print("Array of integers from 10 to 60 with a step of 5 :\n",arr5)

Array of integers from 10 to 60 with a step of 5 :
 [10 15 20 25 30 35 40 45 50 55 60]


Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [22]:
arr_str=np.array(['python','numpy','pandas'])

print("Original array:\n",arr_str)

np.char.upper(arr_str)


Original array:
 ['python' 'numpy' 'pandas']


array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [23]:
np.char.lower(arr_str)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [24]:
np.char.title(arr_str)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

Q6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [26]:
word_arr=np.array(['hello','Good morning','numpy'])
print("Original array:\n",word_arr)

Original array:
 ['hello' 'Good morning' 'numpy']


In [27]:
np.char.join('',word_arr)

array(['hello', 'Good morning', 'numpy'], dtype='<U12')

Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [28]:
import numpy as np
arr_2d1=np.array([[1,2,3],[4,5,6]])
arr_2d2=np.array([[6,9,8],[7,6,4]])
print("Array 1 :\n",arr_2d1)

Array 1 :
 [[1 2 3]
 [4 5 6]]


In [29]:
print("Array 2 :\n",arr_2d2)

Array 2 :
 [[6 9 8]
 [7 6 4]]


In [30]:
#Element wise subtraction
np.subtract(arr_2d1,arr_2d2)

array([[-5, -7, -5],
       [-3, -1,  2]])

In [31]:
#Element wise addition
np.add(arr_2d1,arr_2d2)

array([[ 7, 11, 11],
       [11, 11, 10]])

In [32]:
#Element wise multiplication
np.multiply(arr_2d1,arr_2d2)

array([[ 6, 18, 24],
       [28, 30, 24]])

In [34]:
#Element wise division
np.divide(arr_2d1,arr_2d2)

array([[0.16666667, 0.22222222, 0.375     ],
       [0.57142857, 0.83333333, 1.5       ]])

Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [35]:
identity_matrix=np.eye(5)
print("5x5 Identity matrix :\n",identity_matrix)

5x5 Identity matrix :
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [36]:
np.diag(identity_matrix)

array([1., 1., 1., 1., 1.])

Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [37]:
ran_arr=np.random.randint(0,1000,size=100)
print("Random Generated array are:\n",ran_arr)

Random Generated array are:
 [860 733 569 189 583 138 379 736 560 438 628 268 926 765 878 277 108 412
 177  87 672 721 364 344 782 226 764 283 104 115 114 550 188 311 842 319
 218 254 441 922 539 368 648 714 786 584 177 140 636 847 287 561  89 964
 461 274 278 574 248 604 736  54 327  41 817 461 932 955 501 899 726 399
  60 326 932 261 129 328 913 786 576 545 990 562 218 356 936 354 778 251
 915 896 403 891 283 448 941 712 986 583]


In [38]:
def is_prime(n):
  if n<2:
    return False
  for i in range(2,int (np.sqrt(n))+1):
    if n% i==0:
      return False
  return True

prime_number=[num for num in ran_arr if is_prime(num)]
print("Prime numbers in the array are:\n",prime_number)

Prime numbers in the array are:
 [np.int32(733), np.int32(569), np.int32(379), np.int32(277), np.int32(283), np.int32(311), np.int32(89), np.int32(461), np.int32(41), np.int32(461), np.int32(251), np.int32(283), np.int32(941)]


Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [39]:
mat_rix=np.arange(1,10).reshape(3,3)
print("Matrix :\n",mat_rix)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [40]:
#Sum of each row
np.sum(mat_rix,axis=1)

array([ 6, 15, 24])

In [41]:
#Sum of each column
np.sum(mat_rix,axis=0)

array([12, 15, 18])